[package]
name = "xs_rusty_file_transfer"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xs-rust-library = { git = "https://github.com/CaptainOachkatzl/XSRustLibrary" }
directories = { version = "6.0" }
bytemuck = { version = "*", features = ["derive"] }
eframe = "*"
egui = "*"
env_logger = "*"
